<template>
  <div :id="_uid"></div>
</template>

<script>
import justgage from 'justgage'

export default {
  props: {
    value: Number,
    max: Number,
    options: {
      type: Object,
      default: () => ({}),
    },
  },

  data: () => ({
    g: null,  // gauge object
  }),

  mounted () {
    // JustGage requires an element ID to init properly. Use Component unique ID
    // (generated by Vue.js) to distinguish gauges on the same page.
    this.options.id = this._uid
    if (this.value) this.options.value = this.value
    if (this.max) this.options.max = this.max
    this.g = new JustGage(this.options)
  },

  watch: {
    // Refresh gauge when value or max are updated
    value (val) {
      this.g.refresh(val)
    },
    max (val) {
      this.g.refresh(this.value, val)
    },
  }
}
</script>
